language: java

install:
  - ./create-secret-file.sh
  - mvn clean test

notifications:
  email:
    on_success: never

# whitelist
branches:
  only:
    - master

after_success:
  - mvn clean cobertura:cobertura coveralls:report