.\" Manpage for tmc.
.\" Contact massimo.zappino@gmail.com to correct errors or typos.
.TH tmc 1 "22 Mar 2015" "0.1-SNAPSHOT" "tmc man page"
.SH NAME
tmc \- tagmycode-cli
.SH SYNOPSIS
tmc [options]
.SH DESCRIPTION
Tmc - TagMyCode-Cli is a tool
.SH OPTIONS
usage: tmc

-a,--add <filename>   Create a snippet from file

-h,--help             Show help message

   --info             Show account information

-l,--languages        Show languages

   --login            Authenticate to TagMyCode.com

-p,--private          Set the snippet private

-v,--version          Display version information
.SH BUGS
No known bugs.
.SH HOMEPAGE
https://tagmycode.com
.SH AUTHOR
Massimo Zappino (massimo.zappino@gmail.com)